### ISSUE TITLE
After installation / deinstallation, login via authplain is dead slow

### ISSUE THREAD

**Issue by tmo26** [gdirch/authyubikey#3]
Dokuwiki version: Release 2020-07-29 "Hogfather"
Template bootstrap3: Template v2020-08-28 (develop/20210113)
Authyubikey version: 2017-01-03

**Issue:** After installation, configuration and unsuccessfull tryout, authyubikey has been uninstalled again. After this, authplain is dead slow, taking >2,5min to log in.
OAuth login via github however is still fast as before.

Seems that the installation of authyubikey has done some changes to the dokuwiki installation which can not be reversed by simply uninstalling the plugin.

How can authplain be brought back to normal performance, i.e. login within seconds instead of minutes?

**Comment by gdirch** [comment]
Currently I have no idea what could have happened  to your installation. Normally plugins are simply installed in a separate directory (dokuwiki_home/lib/plugins/authyubikey) with no impact to other modules of Dokuwiki. By simply removing this directory a plugin like authyubikey should be removed safe and completely.

Sorry, but I do not support this plugin any more since 2016 (Dokuwiki version "Elenor Of Tsort") because of missing time ...

**Comment by gdirch** [comment]
I've just tested this issue. I can confirm that authyubikey is not compatible with Dokuwiki version Hogfather :-(

But I've no trouble after removing my plugin. Logging in with authplain is fast as before instalation. Do you have checked the correct setting of authtype in Dokuwiki's configuration?

**Comment by gdirch** [comment]
I've actualized the compatibilty list of the Dokuwiki plugin page [https://www.dokuwiki.org/plugin:authyubikey](https://www.dokuwiki.org/plugin:authyubikey)

**Comment by tmo26** [comment]
Seems that the "dead slow" situation was a transient one. I can only speculate that this was caused by an unfortunate chain of coincidences (temporary high traffic, paired with a caching issue, and on top plugin installation and uninstallation) that resulted in this slowness.

> Sorry, but I do not support this plugin any more since 2016 (Dokuwiki version "Elenor Of Tsort") because of missing time ...

You could announce on the plugin page that you are no longer maintaining this plugin and that you are searching for someone to take over the further development. Would be great if someone picks it up and keeps this plugin alive! :)
